services:
  postgres:
    image: postgres:15-alpine
    container_name: cadastro_db
    restart: on-failure
    environment:
      POSTGRES_DB: cadastro_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cadastro_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: postgres
      DB_DATABASE: cadastro_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: cadastro_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data: